export const PrivacyPolicyModalContent = <div className="flex h-full flex-col">
    <div className="p-8 text-lg font-medium"><strong>Privacy Policy</strong></div>
    <div className="grow space-y-4 overflow-auto p-8 pt-0">
        <p><strong>Effective Date: May 1, 2020</strong></p>
        <p>SparkleUp (“SparkleUp”) is committed to protecting our visitors’ and members’ privacy. This Privacy Policy describes the types of information that SparkleUp collects from and about you when you visit our website, <a href="https://www.sparkleup.us/">www.sparkleup.us</a> (“Site”), mobile app (“App”), mobile messaging services, and or other online or offline communications (collectively, the “Services”). This Privacy Policy also explains how SparkleUp may use and disclose such information, and your ability to control certain uses of it.</p>
        <p>By using the Services, you agree to the collection, use, and disclosure of your information as described in this Privacy Policy, and agree to the SparkleUp Terms of Use which are incorporated by reference. If you do not agree, please do not access or use the Services.</p>
        <p><strong>1. INFORMATION WE COLLECT</strong></p>
        <p><strong>1.1 Information You Provide</strong></p>
        <p>SparkleUp collects information from you when you choose to share it with us. This may include when you use our Services, register or create an online account with or through the Services, make a purchase, request information from us, sign up for newsletters, text messages, or our email list, use our cleaning and related services, enter into sweepstakes or other promotion, fill out a survey, request customer support, or otherwise communicate with or contact us. The information we collect may include your name, email address, password, telephone or mobile number, address (for pickup and delivery), zip code, and photo.</p>
        <p>You may also provide us with certain information in connection with specification transactions:</p>
        <p>Information You Provide When You Make a Purchase. If you make a purchase from us, we collect a credit/debit card number and related financial information (such as CVV, expiration date, and billing address), or other payment information (such as via PayPal or Apple Pay), depending on the form of payment you choose.</p>
        <p>Information About Your Clothing. We may also collect information on the clothes you are giving us for cleaning, including type, service requested, brand, color, size, and photos. We do this to provide you with an enhanced experience when using the Service, such as sending an itemized list of items we picked up for cleaning, and providing you with customized offers or promotions based on the information we collect about your clothing.</p>
        <p>Referring a Friend. If you choose to refer a friend through the Services, we will ask for your friend&#8217;s contact information. We will a message to your friend inviting him or her to sign-up for SparkleUp&#8217;s service or visit the Site or App. We store this information to send the referral message(s) and track the success of our referral program.</p>
        <p>Information You Provide Through Social Media. You may also be given the option to link to your Facebook or other social media account through the Services. When you do, we may automatically receive certain information about you based on your registration and privacy settings on those third party services.</p>
        <p><strong>1.2 Information Automatically Collected</strong></p>
        <p>Whenever you visit or interact with the Services, SparkleUp, as well as any third-party advertisers and/or service providers, may use a variety of technologies that automatically or passively collect information about your online activity. This information may be collected in the following ways:</p>
        <p>Usage Information: We may use a variety of technologies such as cookies, web beacons, pixel tags, log files, local shared objects (Flash cookies), HTML5 cookies, or other technologies to collect certain information about visitors to, and users of, our Services and interactions with our emails and online and mobile advertisements, and to allow SparkleUp to keep track of analytics and certain statistical information. This includes, but is not limited to, your browser type, device type, operating system, software version, the domain name from which you accessed the Services, the date and time you visit the Services, the areas or pages of the Services that you visit, the amount of time you spend viewing or using the Services, the number of times you return to the Services, other click-stream or site usage data, emails that you open, forward or click-through to our Services, and other sites that you may visit.</p>
        <p>Device Information: We may automatically collect your IP address or other unique identifier (“Device Identifier”) for the computer, mobile device, tablet or other device (collectively, “Device”) you use to access the Services, including the hardware model and mobile network information. We may use a Device Identifier to, among other things, provide the Services, help diagnose problems with our servers, analyze trends, track users’ web page, email and mobile application movements/activities, help identify or gather broad demographic information for aggregate use, and retarget online and mobile advertisements to you across computers or devices you may use.</p>
        <p>Geolocation Information: If you choose to turn on your Bluetooth, Wi-Fi or other geolocation functionality when you use our App, we may collect and use your geolocation information so that you are able to view when our drivers are close to your location, set your pick up location if you are at a different address then you have saved in your account, and allow our drivers to find the location you wish your clothes to be picked up from.</p>
        <p>Third Party Service Providers. We may use third party service providers to support our Site or App. Some of these service providers may use technology such as cookies, web beacons, pixel tags, log files, Flash cookies, or HTML5 cookies to receive, collect, and store information.</p>
        <p>Third Party Analytic Technologies. We may use third parties’ analytics and tracking tools to better understand who is using the Services, how people are using the Services, how to improve the effectiveness of the Services and related content, and to help us or those third parties serve more targeted advertising to you across the Internet. These tools may use technology such as cookies, web beacons, pixel tags, log files, Flash cookies, HTML5 cookies, or other technologies to automatically collect and store certain information. They may also combine information they collect from your interaction with the Site or App with information they collect from other sources. We do not have access to, or control over, these third parties’ use of cookies or other tracking technologies.</p>
        <p><strong>1.3 Information Collected From Other Sources</strong></p>
        <p>We may acquire information from other trusted sources to update or supplement the information that you provide or that we collect automatically (such as information to validate or update your address or other demographic and lifestyle information). We may use this information to help us maintain the accuracy of the information we collect, to target our communications so that we can inform you of products, services or other offers that may be of interest to you, and for internal business analysis or other business purposes.</p>
        <p><strong>1.4 Combination of Information</strong></p>
        <p>We may combine the information we receive from and about you, including information you provide to us and information we automatically collect through the Services, as well as information collected offline, across other computers or devices that you may use, and from third party sources.</p>
        <p><strong>2. HOW WE USE YOUR INFORMATION</strong></p>
        <p>SparkleUp may use the information we collect from and about you for the following reasons:</p>
        <p>To respond to your requests for cleaning and related services (including to validate, confirm, verify, pickup, fulfill, and deliver your order), and contact and communicate with you when necessary (including providing service-related announcements);<br />To enhance your online shopping experience, including as a way to recognize you and welcome you to the Services, and allow you to view your order history;<br />To review the usage and operations of our Services, develop new products or services, and conduct analysis to enhance or improve our content, products, and services;<br />To provide you with customized Site or App content, targeted offers, and advertising on the Site or App, via email, text message or push notification, or across other websites, mobile applications, social media or online services;<br />To contact you with information, newsletters and promotional materials from SparkleUp or on behalf of our partners and affiliates;<br />To use your data in an aggregated non-specific format for analytical and demographic purposes;<br />To protect the security or integrity of the Services and our business, such as by protecting against and preventing fraud, unauthorized transactions, claims and other liabilities, and managing risk exposure, including by identifying potential hackers and other unauthorized users;<br />To use and disclose your credit/debit card information only to process payments and prevent fraud; and<br />For other purposes disclosed at the time you provide your information or otherwise with your consent.</p>
        <p><strong>3. INFORMATION WE SHARE</strong></p>
        <p>We do not sell, share, rent or trade your personal information or geo-location information other than as disclosed within this Privacy Policy. We may share the information we collect from and about you in the following ways:</p>
        <p>Affiliates: We may share your information with SparkleUp affiliates and subsidiaries for business, operational, promotional and marketing purposes.<br />Service Providers: We may share your information with third party service providers that provide business, professional or technical support functions for us (including to the extent necessary or desirable to pick up or deliver your order or complete your transaction), help us operate our business and the Services, or administer activities on our behalf.<br />Sweepstakes, Contests, and Promotions. If you choose to enter into one of our sweepstakes, contests, or other promotions (a “Promotion”) we may disclose your information to third parties or the public in connection with the administration of such Promotion, as required by law, as otherwise permitted by the Promotion’s official rules, or otherwise in accordance with the terms of this Privacy Policy.<br />Business Partners or Other Trusted Entities: We may share your information with our select business partners, affiliates, and other trusted entities for the purpose of providing you with information on goods or services we believe will be of interest to you. You may, at any time, opt out of receiving such communications by contacting those third parties directly.<br />Legal Matters; Safety: We may access and disclose your information to respond to subpoenas, judicial processes, or government requests and investigations, or in connection with an investigation on matters related to public safety, as permitted by law, or otherwise as required by law. We may disclose your information to protect the security of our Services, servers, network systems, and databases. We also may disclose your information as necessary, if we believe that there has been a violation of our Terms of Use, any other legal document or contract related to our services, or the rights of any third party.<br />Sale or Transfer of Business or Assets: We may sell or purchase assets during the normal course of our business. If another entity acquires us or any of our assets, information we have collected about you may be transferred to such entity. In addition, if any bankruptcy or reorganization proceeding is brought by or against us, such information may be considered an asset of ours and may be sold or transferred to third parties. Should such a sale or transfer occur, we will use reasonable efforts to try to require that the transferee use personal information provided through the Services in a manner that is consistent with this Privacy Policy.<br />Aggregate or Anonymous Non-Personal Information: We may also share aggregate, anonymous, or de-identified non-personal information with third parties for their marketing or analytics uses.<br />Other: We also may share your information as disclosed to you at the time of collection, or otherwise with your consent.</p>
        <p><strong>4. YOUR CHOICES AND OPT-OUTS</strong></p>
        <p>Cookies, Tracking Options and California Do Not Track Disclosures</p>
        <p>Certain parts of our Site and App require cookies. You are free to set your browser or operating system settings to limit certain tracking or to decline cookies, but by doing so, you may not be able to use certain features on the Services or take full advantage of all of our offerings. Please refer to your Web browser’s or operating system’s website or “Help” section for more information on how to delete and/or disable your browser or operating system from receiving cookies or controlling your tracking preferences.</p>
        <p>Our system may not respond to Do Not Track requests or headers from some or all browsers. We may use cookies or other technologies to deliver more relevant advertising and to link data collected across other computers or devices that you may use. To understand your choices for receiving more relevant advertising or to manage your settings, please review the information below:</p>
        <p>To learn more about the use of cookies or other technologies to deliver more relevant advertising and to know your choices with respect to collection and use of the data by these third party tools, you may visit the Network Advertising Initiative’s (NAI) opt-out page at http://www.networkadvertising.org/choices, or Digital Advertising Alliance’s (DAA) opt-out page at http://www.aboutads.info/choices. To opt-out of the use of your mobile device ID for targeted advertising, see http://www.aboutads.info/appchoices.<br />If you wish to prevent your data from being used by Google Analytics, Google has developed the Google Analytics opt-out browser add-on available here.<br />On your mobile device, you may also adjust your privacy and advertising settings to control whether you want to receive more relevant advertising.</p>
        <p><strong>Opt Out Preferences</strong></p>
        <p>We provide our customers with the opportunity to opt-out of having their information used for purposes not directly related to placement, processing, fulfillment, or delivery of a product or service. To opt-out of marketing communications, you may use one of these convenient methods:</p>
        <p>Electronic Promotional Offers. If you do not want to receive emails from us regarding special promotions or offers, you may click the unsubscribe link in the footer of any email, or contact us at care@SparkleUp.com with “Unsubscribe Promotional Offers” in the subject line.<br />Mobile Promotional Offers. When you provide us with your mobile number for marketing purposes, we may send you certain marketing alerts via text message. Standard data and message rates will apply. If you no longer wish to receive mobile alerts from us, you can follow the instructions provided in those messages or otherwise reply “STOP” to any SparkleUp alert.</p>
        <p>Your instructions to limit the use of your information for these purposes will be processed as soon as reasonably practicable. Additionally, we are not responsible for informing third parties (including without limitation our third party service providers or partners) with whom we have already shared your personal information of any changes requested pursuant to this section, or for removing information from or causing information to be removed from the databases or records of such entities</p>
        <p><strong>Access to Your Information</strong></p>
        <p>You may log in to your account page on the Site or App to update your profile, payment information, and preferences, or otherwise email us at <a href="mailto:contact@deluxecleanersnc.com">contact@deluxecleanersnc.com</a>. If you choose to deactivate your account, we may still retain certain information for analytical purposes and recordkeeping integrity, as well as to prevent fraud, resolve disputes, enforce our Terms of Use or other policies, take actions we deem necessary due to technical and legal requirements, and as dictated by constraints related to the security, integrity and operation of our Services.</p>
        <p><strong>5. YOUR CALIFORNIA PRIVACY RIGHTS</strong></p>
        <p>If you are a California resident, you may request information about our disclosure of personal information to third parties or affiliated companies for their direct marketing purposes. To make such a request, please contact us at <a href="mailto:contact@deluxecleanersnc.com">contact@deluxecleanersnc.com</a>. You must put the statement “Your California Privacy Rights” in the subject field. We are not responsible for notices that are not labeled or sent properly, or do not have complete information.</p>
        <p>Non-affiliated third parties are independent from SparkleUp and if you wish to receive information about your disclosure choices or stop communications from such third parties, you will need to contact those non-affiliated third parties directly.</p>
        <p><strong>6. THIRD-PARTY CONTENT, LINKS, AND PLUG-INS</strong></p>
        <p>The Services may have links to third-party websites, which may have privacy policies that differ from our own. We are not responsible for the practices of such sites.</p>
        <p>The Services may also offer you the ability to interact with social plugins from social media sites, which may allow us and/or the social media site to receive data from or about you. In some cases, we may know that you clicked on a social plugin, such as a Twitter Follow button, or receive other information from the social media sites. Similarly, if you have previously provided personal information to a third-party operating a plug-in on the Services, then such third-party may recognize you on the Services. Your use of social network plugins is subject to each social media site’s privacy policy, which may be different from ours, so please read these policies carefully to understand their policies and your options. As with linked sites, we have no control over the information that is collected, stored, or used by social network plugins, and are not responsible for the practices of such sites.</p>
        <p><strong>7. PUBLIC FORUMS</strong></p>
        <p>Any information you may disclose on our Services, in blogs, on message boards, in chat rooms, or on other public areas on the Services or other third-party websites that the Services may link to, becomes public information. Please exercise caution when disclosing personal information in these public areas.</p>
        <p><strong>8. CHILDREN’S PRIVACY</strong></p>
        <p>Protecting children’s privacy is important to us. We do not direct the Services to, nor do we knowingly collect any personal information from, children under the age of thirteen. If SparkleUp learns that a child under the age of thirteen has provided personally identifiable information to the Services, it will use reasonable efforts to remove such information from its files.</p>
        <p><strong>9. DATA SECURITY</strong></p>
        <p>We have taken certain physical, administrative, and technical steps to safeguard the information we collect from and about our customers and visitors and users of our Services. While we make every effort to help ensure the integrity and security of our network and systems, we cannot guarantee our security measures. When you enter sensitive information (such as credit card information) on our forms, we encrypt the transmission of that information using secure socket layer technology (SSL).</p>
        <p><strong>10. REVISIONS TO THIS PRIVACY POLICY</strong></p>
        <p>We reserve the right, at our sole discretion, to change, modify, add, remove, or otherwise revise portions of this Privacy Policy at any time. When we do, we will post the change(s) on the Services. Your continued use of the Services following the posting of changes to these terms means you accept these changes. If we change the Privacy Policy in a material way, we will provide appropriate notice to you.</p>
        <p><strong>11. HOW TO CONTACT US</strong></p>
        <p>If you have any questions or concerns about this Privacy Policy or the practices described herein, you may contact us <a href="mailto:contact@deluxecleanersnc.com">contact@deluxecleanersnc.com </a>or by mail to:</p>
        <p>SparkleUp</p>
        <p>1810 Martin Luther King Jr Pkwy</p>
        <p>Durham, NC 27707</p>
    </div>
</div>;