export const TermsAndConditionsModalContent = <div className="flex h-full flex-col">
    <div className="p-8 text-lg font-medium"><strong>Terms and Conditions</strong></div>
    <div className="grow space-y-4 overflow-auto p-8 pt-0">
        <p><strong>PLEASE NOTE: THESE TERMS OF USE CONTAIN AN ARBITRATION CLAUSE AND CLASS ACTION WAIVER. THE WAIVER AFFECTS HOW DISPUTES WITH THE COMPANY ARE RESOLVED. BY ACCEPTING THESE TERMS OF USE, YOU AGREE TO BE BOUND BY THIS ARBITRATION PROVISION. PLEASE READ IT CAREFULLY.</strong></p>
        <p>These Terms of Use (“Terms”) govern your use of the SparkleUp,(“SparkleUp”) website, <a href="http://deluxecleanersnc.com/">www.DeluxeCleanersNC.com</a> (“Site”), mobile app (“App”), mobile messaging services, and or other online or offline communications (collectively, the “Services”). By using the Services, you agree, without limitation or qualification, to be bound by these Terms and the SparkleUp Privacy Policy. If you do not agree, please do not use the Services.</p>
        <p>SparkleUp may modify these Terms at any time. Your continued usage of the Services will mean you accept those changes, and you agree to comply with all applicable laws and regulations.</p>
        <p>&nbsp;</p>
        <p><strong>1. OUR SERVICES</strong></p>
        <p>SparkleUp provides pick-up and delivery services for dry cleaning, laundry, and related services. SparkleUp interacts with Dry Cleaners, Laundromats, and related partners (“Cleaners”) to clean and care for clothes and other items that you give to SparkleUp. Pick-up and delivery may be requested through the Site or App, or via email or SMS messaging.</p>
        <p><strong>2. ELIGIBILITY</strong></p>
        <p>You must be 18 years of age or older to visit or use the Services in any manner. By visiting or using the Services and/or accepting these Terms of Use, you represent and warrant that you are 18 years or older, and that you have the right, authority, and capacity to agree to and abide by these Terms. You also represent and warrant that you will use the Services in a manner consistent with any and all applicable laws and regulations.</p>
        <p><strong>3. USE OF THE SITE OR APP</strong></p>
        <p><strong>3.1 Use Restrictions</strong></p>
        <p>SparkleUp alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the Services, including all as text, graphics, images, photographs, illustrations, trademarks, trade names, service marks, logos, information obtained from SparkleUp’s licensors, and other materials (“Contents”). These Terms do not convey to you any rights of ownership in or related to the Services or the Content. SparkleUp’s name, logo, and the product names associated with the Services are trademarks of SparkleUp, its affiliated companies or third parties, and no right or license is granted to use them.</p>
        <p>Any use of the Contents not expressly permitted by these Terms is a breach of these Terms and may violate copyright, trademark, and other laws. Except as stated herein, none of the Contents may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means without the prior written permission of SparkleUp or its licensors.</p>
        <p>Subject to your compliance with these Terms, SparkleUp grants you a limited, non-exclusive, non-transferable license: (A) to view, download and print any Content solely for your personal and non-commercial purposes; (B) to view any Content to which you are permitted access solely for your personal and non-commercial purposes; and (C) view and use the Services. You have no right to sublicense the license rights granted in this section, without our prior express, written consent.</p>
        <p>You may not: (i) use, copy, adapt, modify, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, reproduce, transmit, stream, broadcast or otherwise exploit the Services or Content, except as expressly permitted in these Terms; (ii) reuse any Content without first obtaining the written consent of SparkleUp; (iii) “mirror” any Contents contained in the Services or any other server; (iv) use the Services in any manner that could damage, disable, overburden, or impair the Services, or interfere with any other party’s use and enjoyment of the Services; (v) use the Services for any purpose that is unlawful or prohibited by these Terms of Use; or (vi) not attempt to gain unauthorized access to the Services through hacking, password mining or any other means.</p>
        <p>All rights not expressly granted herein are reserved to SparkleUp and its licensors. SparkleUp reserves the right, in its sole discretion, to terminate your access to the Services, or any portion thereof, at any time, for any reason or for no reason at all, without prior notice or any notice.</p>
        <p><strong>3.2 User Submissions</strong></p>
        <p>The personal information you submit to SparkleUp is governed by the Privacy Policy. To the extent there is an inconsistency between the Terms of Use and the Privacy Policy, the Privacy Policy shall govern. We may, in our sole discretion, permit you to post, upload, input, publish, submit or transmit information or material through the Service (“Submission”). Submission will be deemed non-confidential and non-proprietary. Accordingly, SparkleUp shall have the non-exclusive, royalty-free, right to use, copy, distribute and disclose to third parties any Submission for any purpose, in any medium and throughout the world (&#8220;License Grant&#8221;).</p>
        <p>You are solely responsible for your Submission, the consequences of making a Submission, and your reliance on any Submissions. SparkleUp is not responsible for the consequences of any Submission. SparkleUp is not responsible for screening or monitoring Submissions made through the Services by users. If notified by a user of a Submission allegedly in violation of these Terms of Use, SparkleUp may investigate the allegation and determine in good faith and its sole discretion whether to remove such Submission. SparkleUp will have no liability or responsibility to users for performance or nonperformance of such activities.</p>
        <p><strong>3.3 Your Account</strong></p>
        <p>If you use the Services, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your devices. You agree to accept responsibility for all activities that occur under your account or password. SparkleUp reserves the right to refuse service, terminate accounts, remove or edit content, or cancel orders in its sole discretion.</p>
        <p><strong>4. TERMS OF SERVICE</strong></p>
        <p>To use the Services, you must first sign up with SparkleUp. When signing up, we request that you provide SparkleUp with certain personal information so that we can provide you with the requested Services (such information may include name, email address, mobile telephone number, address for pick-up and delivery, and/or credit card data). Upon successful completion of your signing up with SparkleUp, SparkleUp will provide you with a personal account, which may be accessible by you with a password of your choice.</p>
        <p><strong>4.1 Use of the Service</strong></p>
        <p>You warrant that the information you provide to SparkleUp is accurate and complete. SparkleUp is entitled at all times to verify the information that you have provided and to refuse the Services without providing notice.</p>
        <p>You may only access the Services using authorized means. It is your responsibility to check to ensure you are using the correct App and App version for your device. SparkleUp is not liable if you do not have a compatible mobile device or if you download the wrong version of the App for your mobile device. SparkleUp reserves the right to terminate the Services and the use of the App if used with an incompatible or unauthorized device.</p>
        <p><strong>4.2 Payment</strong></p>
        <p>Use of the Site and App is free of charge. SparkleUp reserves the right to introduce a fee for the use of these Services. If SparkleUp decides to introduce such a fee, SparkleUp will inform you accordingly and allow you to either continue or terminate the Services.</p>
        <p>SparkleUp charges for the services that you request, which may include dry cleaning, laundered shirts, wash &amp; fold, or related services (&#8220;Cleaning&#8221;). You agree that you will pay for all Cleaning you purchase through SparkleUp, and that SparkleUp may charge your credit card account as provided by you when registering for the Services for the Cleaning (including any taxes, late fees, or additional fees as applicable) that may be accrued by or in connection with your account. You are responsible for the timely payment of all fees and for providing SparkleUp with a valid credit card account for payment of all fees at all times. Any payment made is non-refundable.</p>
        <p>SparkleUp may use a third-party payment processor (the &#8220;Payment Processor&#8221;) to link your credit card account to the Services. The processing of payments or credits, as applicable, in connection with your use of the Services will be subject to the terms, conditions and privacy policies of the Payment Processor and your credit card issuer in addition to these Terms. SparkleUp is not responsible for any errors by the Payment Processor.</p>
        <p><strong>5. TEXTING TERMS AND CONDITIONS</strong></p>
        <p>You may opt in to receive SparkleUp’s text messages (using autodialer technology) at the mobile number you provide to us. Your consent to receive our promotional texts is not a condition of purchase or use of the cleaning services. Message and data rates may apply. If you have any questions about your text plan or data plan, please contact your wireless provider. You can opt out of receiving our texts by following the instructions provided in those messages or otherwise reply to our texts with the “STOP” command. If you have any questions, you may reply “HELP” to any text from SparkleUp or contact us by texting “HELP” to 746-73.</p>
        <p><strong>6. PROMOTIONS</strong></p>
        <p>Any and all offers or promotions advertised on the Services are void where prohibited, and are subject to the posting of any official rules to such offers or promotions.</p>
        <p><strong>7. LIABILITY</strong></p>
        <p>You understand that there is inherent risk in Cleaning and there is potential for clothing and related items to get lost or damaged. SparkleUp will do its best to ensure situations like this do not happen, and in the instances they do happen, will work with you to help rectify the situation when you provide us with written notification identifying the concern with the Cleaning within fourteen (14) days of receiving your cleaned clothes and items. Without prejudice to the foregoing, and insofar as allowed under mandatory applicable law, SparkleUp’s aggregate liability in no event shall exceed an amount of $1,000 or, where applicable, the equivalent of that amount in the currency used by you for the payment for Cleaning.</p>
        <p>In addition, the information, recommendations and/or services provided to you on or through the Services is for general information purposes only. The use of the Site or the Contents is at your own risk. The Contents in this Site could include technical inaccuracies or typographical errors. SparkleUp may make changes or improvements at any time.</p>
        <p>THE CONTENTS IN THIS SITE ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, SparkleUp DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SparkleUp DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE MATERIAL WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SparkleUp DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF OR THE RESULT OF THE USE OF THE CONTENTS IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT SparkleUp) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.</p>
        <p>TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, SparkleUp ASSUMES NO LIABILITY, WHETHER IN CONTRACT OR TORT, FOR ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING (WITHOUT LIMITATION) DAMAGES FOR LOSS OF ANTICIPATED PROFITS OR REVENUE OR OTHER ECONOMIC LOSS IN CONNECTION WITH OR ARISING FROM ANY ACT OR OMISSION BY SparkleUp, ITS AGENTS, AFFILIATES, JOINT VENTURE PARTNERS, INDEPENDENT CONTRACTORS, OR UNAFFILIATED THIRD PARTIES AS A RESULT OF ANY ACT OR OMISSION IN FULFILLMENT OF OR IN BREACH OF THESE TERMS OF USE OR THE PRIVACY POLICY.</p>
        <p><strong>8. THIRD-PARTY WEBSITES</strong></p>
        <p>The Service may contain hyperlinks to other websites and webpages (“Third-Party Pages”), as well as to text, graphics, videos, images, music, sounds, and information belonging to or originating from other third-parties (collectively, “Third-Party Applications”). The Company does not investigate, monitor, or review any Third-Party Pages or Third-Party Applications to ensure their accuracy, completeness, or appropriateness. The Company is not responsible for the Third-Party Pages or any Third-Party Applications accessed through the Services. You agree that SparkleUp shall have no liability with respect to any loss or damage of any kind incurred as a result of any dealings between you and any third party, or as a result of the presence of such third party on the Site.</p>
        <p>The inclusion of any hyperlinks to any Third-Party Pages or Third-Party Applications on the Service does not indicate SparkleUp’s approval or endorsement thereof. These links are provided solely as a convenience or benefit to users. Your interactions with a third party on the Services, or based on such third party’s participation or presence on the Services, are solely between you and the third party. SparkleUp makes no representations or warranties with respect to the content, ownership, or legality of any such linked third party website. If you choose to leave the Services to access any Third-Party Pages or Third-Party Applications, you do so at your own risk. Please note that these other websites or apps may send their own cookies to users, collect data or solicit personal information, and you are therefore advised to check the terms of use or privacy policies on those websites prior to using them.</p>
        <p><strong>9. INDEMNITY</strong></p>
        <p>You agree to defend, indemnify, and hold SparkleUp, its affiliates, its licensors, and each of their officers, directors, other users, employees, attorneys, agents, and partners harmless from and against any claims, costs, actions, demands, damages, losses, liabilities, expenses, and settlements including, without limitation, reasonable legal and accounting fees, arising out of or in connection with: (a) your violation or breach of any term of these Terms or any applicable law or regulation, whether or not referenced herein; (b) your violation of any rights of any third party, or (c) your misuse of the Services.</p>
        <p><strong>10. MODIFICATION OR SUSPENSION OF THE SITE</strong></p>
        <p>You agree that SparkleUp may, in its sole discretion and at any time, modify, discontinue, or suspend its operation of the Services, any part thereof or any Contents, temporarily or permanently, without notice or liability to you.</p>
        <p><strong>11. GENERAL</strong></p>
        <p>SparkleUp makes no claims that the Contents are appropriate or may be downloaded outside of the United States. Access to the Contents may not be legal by certain persons or in certain countries. If you access the Services from outside the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction. The following provisions survive the expiration or termination of these Terms of Use for any reason whatsoever: Liability of SparkleUp and its Licensors and Partners, Use Restrictions, User Submissions, Submission of Ideas, Indemnity, Applicable Laws, and Complete Agreement.</p>
        <p><strong>12. APPLICABLE LAWS</strong></p>
        <p>These Terms of Use are governed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions. You and SparkleUp hereby expressly consent and submit to the exclusive jurisdiction of the state and federal courts of San Francisco, California for the adjudication or disposition of any claim, action or dispute arising out of these Terms of Use. If any provision of these Terms of Use is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect. No waiver of any of these Terms of Use shall be deemed a further or continuing waiver of such term or condition or any other term or condition.</p>
        <p><strong>13. MANDATORY AGREEMENT TO ARBITRATE ON AN INDIVIDUAL BASIS</strong></p>
        <p>Any and all controversies, disputes, demands, counts, claims, or causes of action (including the interpretation and scope of this clause, and the arbitrability of the controversy, dispute, demand, counts, claim, or cause of action) between you and the Company or the Company&#8217;s employees, agents, successors, or assigns, shall exclusively be settled through binding and confidential arbitration, except that you or the Company may take claims to small claims court if the dispute qualifies for hearing by such a court. In addition, each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party&#8217;s copyrights, trademarks, trade secrets, patents, or other intellectual property rights.</p>
        <p>There is no judge or jury in arbitration and arbitration procedures are simpler and more limited than rules applicable in court. YOU ACKNOWLEDGE AND AGREE THAT, APART FROM THE NARROW EXCEPTIONS ABOVE, YOU AND THE COMPANY ARE EACH WAIVING YOUR RIGHTS TO SUE IN COURT, INCLUDING RIGHTS TO RECEIVE A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION LAWSUIT, CLASS-WIDE ARBITRATION, PRIVATE ATTORNEY-GENERAL ACTION, OR ANY OTHER REPRESENTATIVE PROCEEDING.</p>
        <p>Arbitration shall be subject to the U.S. Federal Arbitration Act and federal arbitration law, and shall be conducted by Judicial Arbitration Mediation Services, Inc. (“JAMS”) pursuant to the JAMS Streamlined Arbitration Rules &amp; Procedures effective July 1, 2014 (the “JAMS Rules”) and as modified by this agreement to arbitrate.. The JAMS Rules, including instructions for bringing arbitration, are available on its website at http://www.jamsadr.com/rules-streamlined-arbitration. The Minimum Standards are available at http://www.jamsadr.com/consumer-arbitration/.</p>
        <p>You and the Company must abide by these rules: (a) the arbitration shall be conducted on an individual basis and not in a class, consolidated or representative action and the arbitrator shall not award class-wide relief; (b) the Company will pay its arbitration costs as required by JAMS rules, and in the event that you are able to demonstrate that the costs of arbitration will be prohibitive as compared to costs of litigation, the Company will pay as much of your arbitration filing and hearing fees as the arbitrator deems is necessary to prevent the arbitration from being cost-prohibitive as compared to the cost of litigation; (c) the arbitrator may award any individual relief or individual remedies that are permitted by applicable law; and (d) each side pays his, her or its own attorneys&#8217; fees and costs unless the claim(s) at issue permit the prevailing party to be paid its fees and litigation costs, and in such instance, the fees and costs awarded shall be determined by the applicable law.</p>
        <p>With the exception of subpart (a) in the paragraph above, if any part of this arbitration provision is deemed invalid, unenforceable or illegal, then the balance of this arbitration provision shall remain in effect and be construed in accordance with its terms as if the invalid, unenforceable, or illegal provision were not contained. If, however, subpart (a) in the paragraph above is found invalid, unenforceable or illegal, then the entirety of this arbitration provision shall be null and void. If for any reason a claim proceeds in court rather than in arbitration, the dispute shall be exclusively brought in state or U.S. federal court in California.</p>
        <p><strong>14. NOTICE AND TAKE-DOWN PROCEDURES</strong></p>
        <p>If you believe any Submission accessible on or from the Site infringes your copyright, you may request removal of those materials (or access thereto) from this Site by contacting us (address identified below) and providing the following information: (A) identification of the copyrighted work that you believe to be infringed. Please describe the work, and where possible include a copy or the location (e.g., URL) of an authorized version of the work; (B) identification of the Submission that you believe to be infringing and its location; (C) your name, address, telephone number, and email address; (D) a statement that you have a good faith belief that the complained of use of the work is not authorized by the copyright owner, its agent, or the law; (E) a statement that the information you have supplied is accurate, and indicating that “under penalty of perjury,” you are the copyright owner or authorized representative; and (F) signature or the electronic equivalent from the copyright holder or authorized representative.</p>
        <p>Our address for copyright issues relating to this website is as follows:</p>
        <p>SparkleUp</p>
        <p>1810 Martin Luther King Jr Pkwy</p>
        <p>Durham, NC 27707</p>
        <p>Attn: Customer Care</p>
        <p>In an effort to protect the rights of copyright owners, SparkleUp maintains a policy for the termination, in appropriate circumstances, of users of this Site who are repeat infringers.</p>
        <p><strong>15. INVALIDITY; MISCELLANEOUS</strong></p>
        <p>If any part of these Terms is determined to be invalid or unenforceable pursuant to applicable law, including, without limitation, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms will continue in full force and effect. Only you and SparkleUp are entitled to enforce these Terms. No third party will be entitled to enforce any of the terms and conditions herein.</p>
        <p><strong>16. COMPLETE AGREEMENT</strong></p>
        <p>Except as expressly provided in a particular notice or disclaimer posted by or on behalf of SparkleUp on the Services, these Terms, including the Privacy Policy, constitute the entire agreement between you and SparkleUp with respect to the use of the Services and Contents.</p>

    </div>
</div>;